"""
Phase 2: QLoRA Fine-Tuning. Run after generating synthetic_qa.jsonl.

WARNING: 
Executing this script on a machine without a dedicated CUDA GPU (Nvidia) 
with at least 4-6GB of VRAM will crash your system due to Out-Of-Memory errors.
It is highly recommended to run this on a cloud instance with an A10 or A100.
"""

import os
import torch
import argparse

try:
    from unsloth import FastLanguageModel
    from trl import SFTTrainer, SFTConfig
    from datasets import load_dataset
except ImportError:
    print("Warning: Fine-tuning libraries not fully installed. Make sure to pip install unsloth trl datasets.")

def run_finetuning(model_id="unsloth/Qwen2.5-Coder-3B-Instruct-bnb-4bit", dataset_path="synthetic_qa.jsonl", output_dir="results", dry_run=False, epochs=4):
    print(f"Loading Base Model: {model_id} via Unsloth...")
    
    # Load model and tokenizer via Unsloth
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_id,
        max_seq_length=2048,
        dtype=None,
        load_in_4bit=True,
    )

    # Do NOT leave pad_token as <|endoftext|> for Qwen
    if tokenizer.pad_token == "<|endoftext|>" or tokenizer.pad_token is None:
        tokenizer.pad_token = "<|fim_pad|>"
    
    # Ensure EOS token is correctly set for Qwen
    tokenizer.eos_token = "<|im_end|>"

    # Prepare for LoRA
    model = FastLanguageModel.get_peft_model(
        model,
        r=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        lora_alpha=64,
        lora_dropout=0.0, # Unsloth optimizes for 0 dropout
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )
    print(f"Trainable parameters set up for Unsloth.")

    print(f"Loading Dataset: {dataset_path}...")
    # Load the JSONL dataset generated by data/synth.py
    dataset = load_dataset("json", data_files=dataset_path, split="train")

    # Apply the tokenizer's chat template to the "messages" column
    def formatting_prompts_func(examples):
        texts = [tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False) for messages in examples["messages"]]
        return {"text": texts}
    
    dataset = dataset.map(formatting_prompts_func, batched=True)
    dataset = dataset.remove_columns(["messages"])

    if dry_run:
        print("\n--- DRY RUN: Printing first 3 formatted rows ---")
        for i in range(min(3, len(dataset))):
            print(f"\nRow {i+1}:\n{dataset[i]['text']}")
        print("\nDry run complete. Exiting without training.")
        return

    cfg = SFTConfig(
        output_dir=output_dir,
        num_train_epochs=epochs,
        per_device_train_batch_size=4,
        gradient_accumulation_steps=8,
        learning_rate=2e-4,
        bf16=True, 
        logging_steps=10, 
        save_strategy="epoch",
        max_seq_length=2048,
        packing=False,
    )

    trainer = SFTTrainer(
        model=model, 
        args=cfg,
        train_dataset=dataset,
        dataset_text_field="text",
        processing_class=tokenizer,
    )

    print("Starting QLoRA Training...")
    if torch.cuda.is_available():
        trainer.train()
    else:
        raise EnvironmentError("CUDA GPU required for training. Aborting.")
    
    print(f"Saving LoRA adapter to {output_dir}/adapter...")
    model.save_pretrained(f"{output_dir}/adapter")
    tokenizer.save_pretrained(f"{output_dir}/adapter")
    
    # GGUF saving requires llama.cpp to be installed - keeping commented
    # model.save_pretrained_gguf(f"{output_dir}/gguf", tokenizer, quantization_method="q4_k_m")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run QLoRA fine-tuning for Python code understanding.")
    parser.add_argument("--model", type=str, default="unsloth/Qwen2.5-Coder-3B-Instruct-bnb-4bit", help="Base model ID")
    parser.add_argument("--data", type=str, default="synthetic_qa.jsonl", help="Path to JSONL dataset")
    parser.add_argument("--out", type=str, default="results", help="Output directory")
    parser.add_argument("--epochs", type=int, default=4, help="Number of training epochs")
    parser.add_argument("--dry-run", action="store_true", help="Format and print data without training")
    
    args = parser.parse_args()
    
    run_finetuning(
        model_id=args.model,
        dataset_path=args.data,
        output_dir=args.out,
        dry_run=args.dry_run,
        epochs=args.epochs
    )
